NAME = "JDBCExample"

all:
	@echo "Compiling..."
	javac *.java

run: all
	@echo "Running..."
	java -cp 'postgresql-9.4.1208.jre6.jar:.' $(NAME) postgres.student.cs 5432 d3son d3son Ehddnths93

clean:
	rm -rf *.class